name: Unit Test
on: [push]
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Node@16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Run JUnit with Maven
        run: mvn test --batch-mode --fail-at-end
      - name: Run Jest with NPM
        run: npm test
      - name: Surefire Report
        if: success() || failure()    # run this step even if previous step failed
        uses: ScaCap/action-surefire-report@v1.0.5
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: target/test-results/TESTS-results-jest.xml    # Path to test results
          reporter: jest-junit        # Format of test results

